# Generated by Django 4.0.6 on 2022-07-20 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_order_user_p2porder_user_wallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.p2porder'),
        ),
        migrations.AddField(
            model_name='p2porder',
            name='category',
            field=models.CharField(choices=[('CM', 'Crypto Merchange'), ('FV', 'Food Vendor'), ('DP', 'Delivery Personnel'), ('HS', 'Hair Stylist'), ('MS', 'Mechanical Service'), ('MU', 'Music'), ('SM', 'Social Media Influencers')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='p2porder',
            name='payment',
            field=models.CharField(choices=[('TR', 'Bank Transfere'), ('CD', 'Card Payment')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
