# Generated by Django 4.0.6 on 2022-07-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_order_user_order_order_p2porder_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='ADA',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='BNB',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='BTC',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='DOGE',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='ETH',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='LTC',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='MATIC',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='SAPA',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='SHIB',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='XRP',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
    ]
