# Generated by Django 4.0.6 on 2022-07-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_wallet_quantity_wallet_tokens_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2porder',
            name='token',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tokens',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
